version: '3.8'

services:
  storage-db-local:
    image: mysql:8.0
    container_name: storage-db-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor_password
      MYSQL_DATABASE: storagedb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
